"""empty message

Revision ID: 008c3e47787d
Revises: ba42731a3c93
Create Date: 2025-04-12 12:55:05.067805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008c3e47787d'
down_revision = 'ba42731a3c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lider', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_lider')

    # ### end Alembic commands ###
