"""empty message

Revision ID: 01d0f2acfd74
Revises: 9672de44fc2f
Create Date: 2025-03-18 20:44:59.693513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01d0f2acfd74'
down_revision = '9672de44fc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        # Update existing values in the game column
        batch_op.execute("UPDATE team SET game = 'league_of_legends' WHERE game = 'League of Legends'")
        batch_op.execute("UPDATE team SET game = 'valorant' WHERE game = 'Valorant'")

        batch_op.alter_column('game',
               existing_type=sa.VARCHAR(length=80),
               type_=postgresql.ENUM('league_of_legends', 'valorant', name='gameenum'),
               existing_nullable=False,
               postgresql_using="game::gameenum")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('game',
               existing_type=postgresql.ENUM('league_of_legends', 'valorant', name='gameenum'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
