"""empty message

Revision ID: 07ffadafdbaf
Revises: 5bb4c6f0261f
Create Date: 2025-05-24 18:04:29.328230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ffadafdbaf'
down_revision = '5bb4c6f0261f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('started', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tournament', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    op.drop_column('tournament', 'started')
    # ### end Alembic commands ###
