"""empty message

Revision ID: 085a6ba96fe8
Revises: 3018e5a1c9ae
Create Date: 2025-06-29 14:15:02.289377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085a6ba96fe8'
down_revision = '3018e5a1c9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('match_format', sa.String(length=50), nullable=False))
    op.add_column('tournament', sa.Column('final_format', sa.String(length=50), nullable=False))
    op.add_column('tournament', sa.Column('custom_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'custom_rules')
    op.drop_column('tournament', 'final_format')
    op.drop_column('tournament', 'match_format')
    # ### end Alembic commands ###
