"""empty message

Revision ID: 13b90e2da2b2
Revises: 1961f6e1ad13
Create Date: 2025-03-17 18:21:42.217606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b90e2da2b2'
down_revision = '1961f6e1ad13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=80), nullable=False),
    sa.Column('tournament', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
