"""empty message

Revision ID: 297572f68950
Revises: f861116041fc
Create Date: 2025-05-27 16:50:49.903987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297572f68950'
down_revision = 'f861116041fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
