"""empty message

Revision ID: 3018e5a1c9ae
Revises: 88533b5471c2
Create Date: 2025-06-20 02:15:22.965373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3018e5a1c9ae'
down_revision = '88533b5471c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('payment', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment', 'bank', ['bank_id'], ['id'])
    op.drop_column('payment', 'bank')
    op.create_unique_constraint(None, 'tournament', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    op.add_column('payment', sa.Column('bank', postgresql.ENUM('banco_de_venezuela', 'mercantil', 'banesco', 'provincial', 'bnc', 'banco_plaza', 'banco_exterior', 'bancaribe', name='bankenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'bank_id')
    op.drop_table('bank')
    # ### end Alembic commands ###
