"""empty message

Revision ID: 3500b0a045b0
Revises: aa3f4413d3ea
Create Date: 2025-03-18 18:03:56.676160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3500b0a045b0'
down_revision = 'aa3f4413d3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE gameenum AS ENUM ('league_of_legends', 'valorant')")
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', postgresql.ENUM('league_of_legends', 'valorant', name='gameenum', create_type=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('game')
    op.execute("DROP TYPE gameenum")

    # ### end Alembic commands ###
