"""empty message

Revision ID: 3772507e150c
Revises: 90082a3071ef
Create Date: 2025-05-20 19:42:31.997703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772507e150c'
down_revision = '90082a3071ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'is_active')
    # ### end Alembic commands ###
