"""empty message

Revision ID: 421e5c5b0104
Revises: 297572f68950
Create Date: 2025-06-01 12:53:34.660071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421e5c5b0104'
down_revision = '297572f68950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rate > 0', name='check_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payment', sa.Column('amount_usd', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('amount_bs', sa.Integer(), nullable=True))
    op.drop_column('payment', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payment', 'amount_bs')
    op.drop_column('payment', 'amount_usd')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
