"""empty message

Revision ID: 424b50e8460d
Revises: 2b0b7db754aa
Create Date: 2025-02-10 21:59:07.974849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424b50e8460d'
down_revision = '2b0b7db754aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'player', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'player', name='roleenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
