"""empty message

Revision ID: 472451ef9652
Revises: 07ffadafdbaf
Create Date: 2025-05-24 18:12:31.692491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472451ef9652'
down_revision = '07ffadafdbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('num_teams', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'num_teams')
    # ### end Alembic commands ###
