"""empty message

Revision ID: 4a2763a8e874
Revises: 4bab911ef976
Create Date: 2025-06-01 23:34:02.377826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a2763a8e874'
down_revision = '4bab911ef976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('team1_stats_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('match', sa.Column('team2_stats_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'team2_stats_data')
    op.drop_column('match', 'team1_stats_data')
    # ### end Alembic commands ###
