"""empty message

Revision ID: 4ee9bced146e
Revises: c1c88c4fe085
Create Date: 2025-05-04 10:50:58.351079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee9bced146e'
down_revision = 'c1c88c4fe085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('cost', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'cost')
    # ### end Alembic commands ###
