"""empty message

Revision ID: 52e231088e2f
Revises: e6971ca65ee0
Create Date: 2025-04-29 23:41:14.809928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52e231088e2f'
down_revision = 'e6971ca65ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('incoming', 'outgoing', name='paymenttypeenum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('bank', postgresql.ENUM('banco_de_venezuela', 'mercantil', 'banesco', 'provincial', 'bnc', 'banco_plaza', 'banco_exterior', 'bancaribe', name='bankenum'), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('payment')
    # ### end Alembic commands ###
