"""empty message

Revision ID: 6f1366f881a4
Revises: 
Create Date: 2025-04-22 12:23:15.765627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f1366f881a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date_start', sa.String(length=50), nullable=False),
    sa.Column('num_max_teams', sa.Integer(), nullable=False),
    sa.Column('game', postgresql.ENUM('league_of_legends', 'valorant', name='gameenum'), nullable=False),
    sa.CheckConstraint('num_max_teams >= 5 AND num_max_teams <= 10', name='num_max_teams_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('game', postgresql.ENUM('league_of_legends', 'valorant', name='gameenum'), nullable=False),
    sa.Column('tournament_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_in_team', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.String(length=120), nullable=True),
    sa.Column('action', postgresql.ENUM('join_team', 'join_tournament', 'do_payment', name='actionenum'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='statusenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('teamID', sa.Integer(), nullable=True),
    sa.Column('tournamentID', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['teamID'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tournamentID'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('tournament')
    # ### end Alembic commands ###
