"""empty message

Revision ID: 71f57c0851bc
Revises: e91c9c207947
Create Date: 2025-05-25 02:20:23.077166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f57c0851bc'
down_revision = 'e91c9c207947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'next_match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'tournament', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    op.alter_column('match', 'next_match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
