"""empty message

Revision ID: 789243e1b810
Revises: 71f57c0851bc
Create Date: 2025-05-25 04:15:12.280799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789243e1b810'
down_revision = '71f57c0851bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('finished', sa.Boolean(), nullable=True))
    op.execute("UPDATE tournament SET finished = False")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'finished')
    # ### end Alembic commands ###
