"""empty message

Revision ID: 8426ef1fd395
Revises: c597706ef5b3
Create Date: 2025-05-20 17:47:32.043548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8426ef1fd395'
down_revision = 'c597706ef5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team__stats', sa.Column('total_kills', sa.Integer(), nullable=True))
    op.add_column('team__stats', sa.Column('total_assists', sa.Integer(), nullable=True))
    op.add_column('team__stats', sa.Column('total_deaths', sa.Integer(), nullable=True))
    op.add_column('team__stats', sa.Column('team_kda', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team__stats', 'team_kda')
    op.drop_column('team__stats', 'total_deaths')
    op.drop_column('team__stats', 'total_assists')
    op.drop_column('team__stats', 'total_kills')
    # ### end Alembic commands ###
