"""empty message

Revision ID: 860e6458affc
Revises: 84f123dbe66f
Create Date: 2025-05-20 15:58:27.821814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860e6458affc'
down_revision = '84f123dbe66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('KDA', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'KDA')
    # ### end Alembic commands ###
