"""empty message

Revision ID: 8d57f89f759b
Revises: 08a6d718b1f6
Create Date: 2025-05-23 19:18:55.763333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d57f89f759b'
down_revision = '08a6d718b1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('otp_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_expires')
    op.drop_column('user', 'otp_code')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
