"""empty message

Revision ID: 90082a3071ef
Revises: 8426ef1fd395
Create Date: 2025-05-20 18:06:29.338450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90082a3071ef'
down_revision = '8426ef1fd395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('team', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team__stats', 'total_kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team__stats', 'total_assists',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team__stats', 'total_deaths',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team__stats', 'team_kda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user__stats', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user__stats', 'kda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user__stats', 'kda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user__stats', 'deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team__stats', 'team_kda',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('team__stats', 'total_deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team__stats', 'total_assists',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team__stats', 'total_kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment', 'reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
