"""empty message

Revision ID: 9796936cfd34
Revises: ebdc8db562e4
Create Date: 2025-05-19 14:26:21.621178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9796936cfd34'
down_revision = 'ebdc8db562e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team__stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('games_win', sa.Integer(), nullable=False),
    sa.Column('games_lose', sa.Integer(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('tournament_win', sa.Integer(), nullable=False),
    sa.Column('tournament_loses', sa.Integer(), nullable=False),
    sa.Column('tournament_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__stats')
    op.drop_table('team__stats')
    # ### end Alembic commands ###
