"""empty message

Revision ID: a7918505905d
Revises: b935b3c984bc
Create Date: 2025-04-18 17:42:32.698575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7918505905d'
down_revision = 'b935b3c984bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('teamID', sa.Integer(), nullable=True),
    sa.Column('tournamentID', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('payment', sa.String(length=120), nullable=True),
    sa.Column('action', postgresql.ENUM('join_team', 'join_tournament', 'do_payment', name='actionenum'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='statusenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
