"""empty message

Revision ID: aa3f4413d3ea
Revises: c44331a3ef5a
Create Date: 2025-03-18 17:24:06.103199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3f4413d3ea'
down_revision = 'c44331a3ef5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_team', sa.Boolean(), nullable=False, server_default='f'))
    op.execute("UPDATE \"user\" SET is_in_team = False WHERE is_in_team IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_in_team')

    # ### end Alembic commands ###
