"""empty message

Revision ID: b935b3c984bc
Revises: 008c3e47787d
Create Date: 2025-04-18 12:16:18.326712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b935b3c984bc'
down_revision = '008c3e47787d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_leader', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Actualiza los valores NULL a False
    op.execute('UPDATE "user" SET is_leader = false WHERE is_leader IS NULL')

    # Elimina el valor predeterminado para futuras inserciones
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_leader', server_default=None)
    # ### end Alembic commands ###
