"""empty message

Revision ID: ba42731a3c93
Revises: da8f68893046
Create Date: 2025-04-05 17:38:53.864263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba42731a3c93'
down_revision = 'da8f68893046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role', existing_type=sa.String(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
