"""empty message

Revision ID: c44331a3ef5a
Revises: b1709862e1b7
Create Date: 2025-03-18 17:07:54.244737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c44331a3ef5a'
down_revision = 'b1709862e1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('team_tournament_id_fkey', type_='foreignkey')
        batch_op.drop_column('tournament_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('team_tournament_id_fkey', 'tournament', ['tournament_id'], ['id'])

    # ### end Alembic commands ###
