"""empty message

Revision ID: c597706ef5b3
Revises: f35c82ffd864
Create Date: 2025-05-20 16:22:31.977769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c597706ef5b3'
down_revision = 'f35c82ffd864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('deaths', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('kda', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'kda')
    op.drop_column('user__stats', 'deaths')
    # ### end Alembic commands ###
