"""empty message

Revision ID: d42cc343b228
Revises: 421e5c5b0104
Create Date: 2025-06-01 13:01:07.595896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42cc343b228'
down_revision = '421e5c5b0104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'amount_usd',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment', 'amount_bs',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'amount_bs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment', 'amount_usd',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
