"""empty message

Revision ID: da8f68893046
Revises: 3d0d17dd08b6
Create Date: 2025-03-30 18:38:14.011408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8f68893046'
down_revision = '3d0d17dd08b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=False))
        batch_op.drop_column('members_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('max_players')

    # ### end Alembic commands ###
