"""empty message

Revision ID: f76329149ed4
Revises: d42cc343b228
Create Date: 2025-06-01 14:35:28.600182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f76329149ed4'
down_revision = 'd42cc343b228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate')
    op.add_column('payment', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_column('payment', 'amount_bs')
    op.drop_column('payment', 'amount_usd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('amount_usd', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('amount_bs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payment', 'amount')
    op.create_table('exchange_rate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('rate > (0)::double precision', name='check_rate_positive'),
    sa.PrimaryKeyConstraint('id', name='exchange_rate_pkey')
    )
    # ### end Alembic commands ###
