"""empty message

Revision ID: f861116041fc
Revises: 3c1a97798d33
Create Date: 2025-05-26 21:07:13.951095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f861116041fc'
down_revision = '3c1a97798d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tournament', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    # ### end Alembic commands ###
